#include<bits/stdc++.h>
using namespace std;
char id[20];
int zh(char x){
	return x-48;
}
int main(){
	printf("请输入您的身份证：\n");
	scanf("%s",id);
	int year,month,day,lenth,pv;
	lenth=strlen(id);
	year=zh(id[6])*1000+zh(id[7])*100+zh(id[8])*10+zh(id[9])*1;
	month=zh(id[10])*10+zh(id[11])*1;
	day=zh(id[12])*10+zh(id[13])*1;
	pv=zh(id[0])*10+zh(id[1])*1;
	if(month>12 || day>31 || lenth!=18){
		printf("输入格式错误，请重新输入：\n");
		scanf("%s",id);
		year=zh(id[6])*1000+zh(id[7])*100+zh(id[8])*10+zh(id[9])*1;
		month=zh(id[10])*10+zh(id[11])*1;
		day=zh(id[12])*10+zh(id[13])*1;
	}
	year=zh(id[6])*1000+zh(id[7])*100+zh(id[8])*10+zh(id[9])*1;
	month=zh(id[10])*10+zh(id[11])*1;
	day=zh(id[12])*10+zh(id[13])*1;
	pv=zh(id[0])*10+zh(id[1])*1;
	if(pv==11){
		printf("地区：北京市\n");
	}
	if(pv==12){
		printf("地区：天津市\n");
	}
	if(pv==13){
		printf("地区：河北省\n");
	}
	if(pv==14){
		printf("地区：山西省\n");
	}
	if(pv==15){
		printf("地区：内蒙古自治区\n");
	}
	if(pv==21){
		printf("地区：辽宁省\n");
	}
	if(pv==22){
		printf("地区：吉林省\n");
	}
	if(pv==23){
		printf("地区：黑龙江省\n");
	}
	if(pv==31){
		printf("地区：上海市\n");	
	}
	if(pv==32){
		printf("地区：江苏省\n");
	}
	if(pv==33){
		printf("地区：浙江省\n");
	}
	if(pv==34){
		printf("地区：安徽省\n");
	}
	if(pv==35){	
		printf("地区：福建省\n");
	}
	if(pv==36){
		printf("地区：江西省\n");
	}
	if(pv==37){
		printf("地区：山东省\n");
	}
	if(pv==41){	
		printf("地区：河南省\n");
	}
	if(pv==42){
		printf("地区：湖北省\n");
	}
	if(pv==43){
	printf("地区：湖南省\n");
	}
	if(pv==44){
		printf("地区：广东省\n");
	}
	if(pv==45){
		printf("地区：广西壮族自治区\n");
	}
	if(pv==46){
		printf("地区：海南省\n");
	}
	if(pv==50){
		printf("地区：重庆市\n");
	}
	if(pv==51){
		printf("地区：四川省\n");
	}
	if(pv==52){
		printf("地区：贵州省\n");
	}
	if(pv==53){
		printf("地区：云南省\n");
	}
	if(pv==54){
		printf("地区：西藏自治区\n");
	}
	if(pv==61){
		printf("地区：陕西省\n");
	}
	if(pv==62){
		printf("地区：甘肃省\n");
	}
	if(pv==63){
		printf("地区：青海省\n");
	}
	if(pv==64){
		printf("地区：宁夏回族自治区\n");
	}
	if(pv==65){	
		printf("地区：新疆维吾尔自治区\n");
	}
	if(pv==71){
		printf("地区：台湾省\n");
	}
	if(pv==81){
		printf("地区：香港特别行政区\n");
	}
	if(pv==91){
		printf("地区：澳门特别行政区\n");
	}else{
		printf("输入格式错误，请重新输入：\n");
		scanf("%s",id);
		pv=zh(id[0])*10+zh(id[1])*1;
	}
	if(pv==11){
		printf("地区：北京市\n");
	}
	if(pv==12){
		printf("地区：天津市\n");
	}
	if(pv==13){
		printf("地区：河北省\n");
	}
	if(pv==14){
		printf("地区：山西省\n");
	}
	if(pv==15){
		printf("地区：内蒙古自治区\n");
	}
	if(pv==21){
		printf("地区：辽宁省\n");
	}
	if(pv==22){
		printf("地区：吉林省\n");
	}
	if(pv==23){
		printf("地区：黑龙江省\n");
	}
	if(pv==31){
		printf("地区：上海市\n");	
	}
	if(pv==32){
		printf("地区：江苏省\n");
	}
	if(pv==33){
		printf("地区：浙江省\n");
	}
	if(pv==34){
		printf("地区：安徽省\n");
	}
	if(pv==35){	
		printf("地区：福建省\n");
	}
	if(pv==36){
		printf("地区：江西省\n");
	}
	if(pv==37){
		printf("地区：山东省\n");
	}
	if(pv==41){	
		printf("地区：河南省\n");
	}
	if(pv==42){
		printf("地区：湖北省\n");
	}
	if(pv==43){
	printf("地区：湖南省\n");
	}
	if(pv==44){
		printf("地区：广东省\n");
	}
	if(pv==45){
		printf("地区：广西壮族自治区\n");
	}
	if(pv==46){
		printf("地区：海南省\n");
	}
	if(pv==50){
		printf("地区：重庆市\n");
	}
	if(pv==51){
		printf("地区：四川省\n");
	}
	if(pv==52){
		printf("地区：贵州省\n");
	}
	if(pv==53){
		printf("地区：云南省\n");
	}
	if(pv==54){
		printf("地区：西藏自治区\n");
	}
	if(pv==61){
		printf("地区：陕西省\n");
	}
	if(pv==62){
		printf("地区：甘肃省\n");
	}
	if(pv==63){
		printf("地区：青海省\n");
	}
	if(pv==64){
		printf("地区：宁夏回族自治区\n");
	}
	if(pv==65){	
		printf("地区：新疆维吾尔自治区\n");
	}
	if(pv==71){
		printf("地区：台湾省\n");
	}
	if(pv==81){
		printf("地区：香港特别行政区\n");
	}
	if(pv==91){
		printf("地区：澳门特别行政区\n");
	}else{
		printf("输入格式错误，请重新输入：\n");
		scanf("%s",id);
		pv=zh(id[0])*10+zh(id[1])*1;
	}
	if(pv==11){
		printf("地区：北京市\n");
	}
	if(pv==12){
		printf("地区：天津市\n");
	}
	if(pv==13){
		printf("地区：河北省\n");
	}
	if(pv==14){
		printf("地区：山西省\n");
	}
	if(pv==15){
		printf("地区：内蒙古自治区\n");
	}
	if(pv==21){
		printf("地区：辽宁省\n");
	}
	if(pv==22){
		printf("地区：吉林省\n");
	}
	if(pv==23){
		printf("地区：黑龙江省\n");
	}
	if(pv==31){
		printf("地区：上海市\n");	
	}
	if(pv==32){
		printf("地区：江苏省\n");
	}
	if(pv==33){
		printf("地区：浙江省\n");
	}
	if(pv==34){
		printf("地区：安徽省\n");
	}
	if(pv==35){	
		printf("地区：福建省\n");
	}
	if(pv==36){
		printf("地区：江西省\n");
	}
	if(pv==37){
		printf("地区：山东省\n");
	}
	if(pv==41){	
		printf("地区：河南省\n");
	}
	if(pv==42){
		printf("地区：湖北省\n");
	}
	if(pv==43){
	printf("地区：湖南省\n");
	}
	if(pv==44){
		printf("地区：广东省\n");
	}
	if(pv==45){
		printf("地区：广西壮族自治区\n");
	}
	if(pv==46){
		printf("地区：海南省\n");
	}
	if(pv==50){
		printf("地区：重庆市\n");
	}
	if(pv==51){
		printf("地区：四川省\n");
	}
	if(pv==52){
		printf("地区：贵州省\n");
	}
	if(pv==53){
		printf("地区：云南省\n");
	}
	if(pv==54){
		printf("地区：西藏自治区\n");
	}
	if(pv==61){
		printf("地区：陕西省\n");
	}
	if(pv==62){
		printf("地区：甘肃省\n");
	}
	if(pv==63){
		printf("地区：青海省\n");
	}
	if(pv==64){
		printf("地区：宁夏回族自治区\n");
	}
	if(pv==65){	
		printf("地区：新疆维吾尔自治区\n");
	}
	if(pv==71){
		printf("地区：台湾省\n");
	}
	if(pv==81){
		printf("地区：香港特别行政区\n");
	}
	if(pv==91){
		printf("地区：澳门特别行政区\n");
	}
	year=zh(id[6])*1000+zh(id[7])*100+zh(id[8])*10+zh(id[9])*1;
	month=zh(id[10])*10+zh(id[11])*1;
	day=zh(id[12])*10+zh(id[13])*1;
	printf("生日：%d年%d月%d日\n",year,month,day);
	int temporary,genger;
	temporary=zh(id[16]);
	if(temporary%2==0){
		genger=2;
	}else{
		genger=1;
	}
	if(genger==1){
		printf("性别：男");
		}
	if(genger==2){
		printf("性别：女 "); 
	}
	return 0;
}
